/**
 * Build CSS files from token definitions
 */
import { themes, hexToRgb } from '../src/colors.js';
import fs from 'fs';
import path from 'path';

// Convert hex to HSL for CSS variables
function hexToHsl(hex) {
  const { r, g, b } = hexToRgb(hex);
  const rNorm = r / 255;
  const gNorm = g / 255;
  const bNorm = b / 255;

  const max = Math.max(rNorm, gNorm, bNorm);
  const min = Math.min(rNorm, gNorm, bNorm);
  let h, s;
  const l = (max + min) / 2;

  if (max === min) {
    h = s = 0;
  } else {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case rNorm:
        h = ((gNorm - bNorm) / d + (gNorm < bNorm ? 6 : 0)) / 6;
        break;
      case gNorm:
        h = ((bNorm - rNorm) / d + 2) / 6;
        break;
      case bNorm:
        h = ((rNorm - gNorm) / d + 4) / 6;
        break;
    }
  }

  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

function generateThemeCSS(themeName, colors) {
  const cssVars = Object.entries(colors)
    .map(([key, value]) => {
      const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
      const hslValue = hexToHsl(value);
      return `  --${cssKey}: ${hslValue};`;
    })
    .join('\n');

  return `/**
 * EVC Theme: ${themeName}
 * Generated by @evc/tokens
 */

@layer base {
  :root {
${cssVars}
    --radius: 0.5rem;
  }

  .dark {
    /* Dark mode overrides - customize per theme */
  }
}
`;
}

// Build themes
const distDir = path.join(process.cwd(), 'dist', 'themes');
fs.mkdirSync(distDir, { recursive: true });

for (const [themeName, colors] of Object.entries(themes)) {
  const css = generateThemeCSS(themeName, colors);
  fs.writeFileSync(path.join(distDir, `${themeName}.css`), css);
  console.log(`✓ Generated ${themeName}.css`);
}

// Generate combined file
const combinedCSS = `/**
 * EVC Tokens - All Themes
 * Import individual themes from @evc/tokens/css/[theme].css
 */

${Object.entries(themes)
  .map(([name, colors]) => `/* Theme: ${name} */\n.theme-${name} {\n${Object.entries(colors)
    .map(([key, value]) => `  --${key.replace(/([A-Z])/g, '-$1').toLowerCase()}: ${hexToHsl(value)};`)
    .join('\n')}\n}`)
  .join('\n\n')}
`;

fs.writeFileSync(path.join(process.cwd(), 'dist', 'tokens.css'), combinedCSS);
console.log('✓ Generated tokens.css');
